[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/api/*"
  to = "https://imageprocessingexamples.netlify.app/api/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"} 